# Uncomment the next line to define a global platform for your project
  platform :ios, '8.0'

target 'Daily' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  inhibit_all_warnings!
  
  pod 'SDWebImage', '~> 4.0.0' 
  pod 'AFNetworking', '~> 3.1.0'
  pod 'MJRefresh'
  pod 'MBProgressHUD'  

  # Pods for Daily

end
